export * from 'src/store/application/_vereadores'
export * from 'src/store/application/_last-posts'
export * from 'src/store/application/_eventos'
export * from 'src/store/application/_videos'
export * from 'src/store/application/_posts'
export * from 'src/store/application/_pages'
